-- ============================================================
-- Seed: Categorias e Produtos Donna FIT
-- Gerado automaticamente da planilha donna-fit-produtos.xlsx
-- ============================================================

-- Categorias
INSERT INTO public.categories (name, slug, sort_order) VALUES
  ('Combos', 'combos', 1),
  ('Carne Vermelha', 'carne-vermelha', 2),
  ('Frango', 'frango', 3),
  ('Sopas e Caldos', 'sopas-e-caldos', 4),
  ('Low Carb', 'low-carb', 5),
  ('Vegetariano', 'vegetariano', 6),
  ('Massas', 'massas', 7),
  ('Peixe', 'peixe', 8),
  ('Adicionais', 'adicionais', 9)
ON CONFLICT (slug) DO NOTHING;

-- Produtos
INSERT INTO public.products
  (sku, name, description, price, image_url, category_id, stock_type, stock_quantity, is_active, sort_order)
VALUES
  ('MARM 01', 'Fricassê De Palmito Com Arroz Branco (350G)', 'Praticidade e sabor para o seu dia a dia! Nosso fricassê de palmito é preparado com um creme leve e cremoso, palmito selecionado e cobertura de queijo, acompanhado de arroz branco soltinho e saboroso ,acompanha batata palha.  ALÉRGICOS: Contém leite. Pode conter ovos, derivados de trigo, soja. CONTÉM LACTOSE. ARROZ: 140G FRICASSÊ DE PALMITO: 175G QUEIJO: 15G BATATA PALHA: 20G', 16.50, 'https://drive.google.com/uc?export=view&id=1l1C0kDExet0Vumv5uc8zx1I8x3s3aQ9x',
   (SELECT id FROM public.categories WHERE slug = 'vegetariano'),
   'avulso', 50, true, 1),
  ('MARM 02', 'Escondidinho de batata doce com carne moída e queijo. (350g)', 'Uma refeição completa, saborosa e pronta para aquecer! Nosso escondidinho é preparado com um purê cremoso de batata-doce e um recheio suculento de carne moída bem temperada, finalizado com queijo para um toque especial de sabor. ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. CONTÉM LACTOSE.  CARNE MOIDA: 120G PURE DE BATATA DOCE: 210G QUEIJO: 20G', 16.00, 'https://drive.google.com/uc?export=view&id=1idciOhIjo9KUPgwgTmVZYrW1xgLrrWkv',
   (SELECT id FROM public.categories WHERE slug = 'carne-vermelha'),
   'avulso', 50, true, 2),
  ('MARM 03', 'Bife a parmegiana com arroz (300g)', 'Uma refeição clássica e irresistível, pronta para aquecer! Nosso bife à parmegiana é preparado com carne macia, empanada e coberta com molho de tomate saboroso e uma generosa camada de queijo. Acompanha arroz branco soltinho, formando uma combinação perfeita para o seu dia a dia. ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. CONTÉM LACTOSE. PODE CONTER GLÚTEN.  BIFE: 100G ARROZ: 110G MOLHO: 70G PRESUNTO: 5G QUEIJO; 15G', 18.00, 'https://drive.google.com/uc?export=view&id=1EcRZ_y_G7P_vkTU8bqau3Ni21_q5gnUY',
   (SELECT id FROM public.categories WHERE slug = 'carne-vermelha'),
   'avulso', 50, true, 3),
  ('MARM 07', 'Bobó de frango com purê de Aipim (350G)', 'Pedaços de frango bem temperados ao molho de leite de coco e azeite de dendê, acompanhados de um purê de Aipim bem cremoso. É uma refeição prática, leve e saborosa para o seu dia a dia.  ALÉRGICOS: CONTÉM LEITE E DERIVADOS. CONTÉM LACTOSE E GLÚTEN. PODE CONTER SOJA, TRIGO, OVO, AMENDOIM E PEIXE.  PURÊ: 180G BOBÓ DE FRANGO: 170G', 14.00, 'https://drive.google.com/uc?export=view&id=1VxUEq9vZ8npJ0D4Zwx_owpXMFCg6bUZa',
   (SELECT id FROM public.categories WHERE slug = 'frango'),
   'avulso', 50, true, 4),
  ('MARM 05', 'Moída com legumes e Arroz (300G)', 'A combinação perfeita de sabor  para o seu dia a dia. Carne moída  soltinha, refogada com cenoura, vagem e ervilha, acompanhada de um arroz leve e saboroso. ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  MOIDA: 160G ARROZ: 140G', 15.00, 'https://drive.google.com/uc?export=view&id=1REEGjQ7NIlCzmePkYQmFzC-IsWEDADU6',
   (SELECT id FROM public.categories WHERE slug = 'carne-vermelha'),
   'avulso', 50, true, 5),
  ('MARM 06', 'Moída Com Legumes e Purê De Abóbora (350G)', 'Carne moída soltinha com legumes (cenoura, ervilha e vagem) acompanhada de um purê de abóbora super cremoso. É uma opção leve, saudável e deliciosa para o seu dia a dia ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  PURÊ: 190G CARNE MOÍDA 160G', 15.50, 'https://drive.google.com/uc?export=view&id=1VCExaLPi4mfrs8KGFbZWbIcx8JoW9M3g',
   (SELECT id FROM public.categories WHERE slug = 'low-carb'),
   'avulso', 50, true, 6),
  ('MARM 04', 'Bobó de frango com purê de batata doce (350G)', 'Pedaços de frango bem temperados ao molho de leite de coco e azeite de dendê, acompanhados de um purê de batata doce bem cremoso. É uma refeição prática, leve e saborosa para o seu dia a dia. ALÉRGICOS: CONTÉM LEITE E DERIVADOS. CONTÉM LACTOSE E GLÚTEN. PODE CONTER SOJA, TRIGO, OVO, AMENDOIM E PEIXE.  PURÊ: 180G BOBÓ DE FRANGO: 170G', 14.00, 'https://drive.google.com/uc?export=view&id=1oBZp5DmKD5PZRLtTuVNGlqqmQqA-NE-s',
   (SELECT id FROM public.categories WHERE slug = 'frango'),
   'avulso', 50, true, 7),
  ('MARM 08', 'Brasileirinho Fit (300G)', 'O sabor mais amado do Brasil na sua versão mais leve! Arroz branco soltinho, feijão carioca bem temperado e um frango desfiado suculento com cenoura. A combinação perfeita e nutritiva.   ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  FRANGO: 100G ARROZ:  100G FEIJÃO: 100G', 14.50, 'https://drive.google.com/uc?export=view&id=1tC7gHDmdhykpvpfmgXc-PgDV0WwMxdJo',
   (SELECT id FROM public.categories WHERE slug = 'frango'),
   'avulso', 50, true, 8),
  ('MARM 09', 'Filé de tilápia ao molho siciliano (350G)', 'Um prato leve, sofisticado e cheio de sabor para renovar o seu menu da semana! Filé de tilápia grelhado, coberto com um cremoso e suave molho de limão siciliano. Acompanha arroz branco soltinho e um mix saudável de legumes picados (cenoura,vagem e grão de bico).  ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  ARROZ: 100G TILÁPIA:110G LEGUMES: 100G MOLHO: 40G', 20.00, 'https://drive.google.com/uc?export=view&id=1OfhXcf6OClXicMDKEND5RptpMTF5H20V',
   (SELECT id FROM public.categories WHERE slug = 'peixe'),
   'avulso', 50, true, 9),
  ('MARM 10', 'Frango a Parmegiana Com Arroz e Legumes (350G)', 'Filé de frango empanado e suculento, coberto com molho de tomate artesanal e muito queijo derretido, acompanhado de arroz soltinho e um mix de legumes coloridos. Comida de verdade, saudável e com aquele gostinho de feita na hora.  ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  FRANGO: 90G ARROZ: 110G LEGUMES 80G MOLHO: 50G PRESUNTO: 5G QUEIJO: 15G', 16.50, 'https://drive.google.com/uc?export=view&id=1WGwRLFVO5Ivhu8OkvQxJrqWDCdcXoKrL',
   (SELECT id FROM public.categories WHERE slug = 'frango'),
   'avulso', 50, true, 10),
  ('MARM 11', 'Caldo De Kenga (400G)', 'Um delicioso creme de aipim, cenoura e mandioquinha, preparado com frango desfiado e bacon,  A combinação perfeita para uma refeição prática e reconfortante a qualquer hora.  ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  SOPA: 400G', 14.00, 'https://drive.google.com/uc?export=view&id=1bvWisr2rZfMSjHbIBnrat3huhwH9h9e2',
   (SELECT id FROM public.categories WHERE slug = 'sopas-e-caldos'),
   'avulso', 50, true, 11),
  ('MARM 12', 'Canja De Galinha (400G)', 'Uma receita clássica, leve e reconfortante! Nossa canja é preparada com frango desfiado, arroz, legumes selecionados e temperos especiais, resultando em um caldo saboroso e nutritivo, perfeito para qualquer momento.  ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN  CANJA:400G', 14.00, 'https://drive.google.com/uc?export=view&id=1vZE5oMrX1EKxJ6bKfQmlUh1cwahGK2y0',
   (SELECT id FROM public.categories WHERE slug = 'sopas-e-caldos'),
   'avulso', 50, true, 12),
  ('MARM 13', 'Espaguete com almôndegas (350G)', 'Uma refeição clássica e cheia de sabor! Nosso espaguete é acompanhado de suculentas almôndegas e coberto com um delicioso molho de tomate artesanal, preparado com ingredientes selecionados e temperos especiais para garantir uma refeição prática e irresistível.  ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN  MASSA: 190G ALMÔNDEGAS: 60G MOLHO: 100G', 17.00, 'https://drive.google.com/uc?export=view&id=1bZhnGZH260rfAwpje_beYZioXc-HBiLX',
   (SELECT id FROM public.categories WHERE slug = 'carne-vermelha'),
   'avulso', 50, true, 13),
  ('MARM 14', 'Bife á Rolê Com Arroz E Feijão Carioca (350G)', 'Uma refeição completa e cheia de sabor! Nosso bife à rolê é preparado com carne macia e bem temperada, acompanhado de arroz soltinho e feijão carioca caseiro, proporcionando uma combinação clássica e deliciosa para o seu dia a dia.  ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  CARNE: 100G ARROZ: 100G FEIJÃO: 90G MOLHO: 60G', 22.00, 'https://drive.google.com/uc?export=view&id=1ZK-QWLx4XwUYzFx5RiwnK558YflSk554',
   (SELECT id FROM public.categories WHERE slug = 'carne-vermelha'),
   'avulso', 50, true, 14),
  ('MARM 15', 'Arroz Carreteiro (300G)', 'Uma refeição prática, saborosa e perfeita para o dia a dia! Nosso arroz carreteiro é preparado com arroz parboilizado soltinho e temperos especiais, garantindo um prato simples e muito gostoso.  ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  ARROZ CARRETEIRO: 300G', 15.00, 'https://drive.google.com/uc?export=view&id=1QFIbzcAVVLSJk2VROWQuMuKlgg974sao',
   (SELECT id FROM public.categories WHERE slug = 'carne-vermelha'),
   'avulso', 50, true, 15),
  ('MARM 16', 'Panqueca De Ricota Com Espinafre (300g)', 'Uma opção leve, saborosa e prática para o seu dia a dia! Nossa panqueca é recheada com ricota e espinafre, envolta em uma massa macia e deliciosa, perfeita para uma refeição rápida e equilibrada.  ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  MASSA: 50G RICOTA E ESPINAFRE: 140G MOLHO: 95G QUEIJO: 15G', 16.00, 'https://drive.google.com/uc?export=view&id=1Qghp37-N78KbDNK9JFCWpPEFfqY_NhmF',
   (SELECT id FROM public.categories WHERE slug = 'vegetariano'),
   'avulso', 50, true, 16),
  ('MARM 17', 'Panqueca De Frango (300G)', 'Uma opção prática, saborosa e perfeita para o dia a dia! Nossa panqueca é recheada com frango desfiado e envolta em uma massa macia e deliciosa, ideal para uma refeição rápida e completa.  ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.   MASSA: 50G FRANGO: 140G MOLHO: 95G QUEIJO: 15G', 16.00, 'https://drive.google.com/uc?export=view&id=1VmRfG7CVTKiKfD2eBuwLZrSpPEPV2J0Y',
   (SELECT id FROM public.categories WHERE slug = 'massas'),
   'avulso', 50, true, 17),
  ('MARM 18', 'Panqueca De Carne', 'Uma opção prática, saborosa e perfeita para o dia a dia! Nossa panqueca é recheada com carne moída e envolta em uma massa macia e deliciosa, ideal para uma refeição rápida e completa.  ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  MASSA: 50G RICOTA E ESPINAFRE: 140G MOLHO: 95G QUEIJO: 15G', 18.00, 'https://drive.google.com/uc?export=view&id=1O3xX_lHy6VL0ecNQf2ekZwjzfjTQgLW2',
   (SELECT id FROM public.categories WHERE slug = 'massas'),
   'avulso', 50, true, 18),
  ('MARM 19', 'Sopa Eslava (400G)', 'Uma opção saborosa e reconfortante para o seu dia a dia! Nossa sopa eslava é cremosa, nutritiva e preparada para oferecer uma refeição prática e cheia de sabor em qualquer momento. SOPA: 385G QUEIJO: 15G', 14.00, 'https://drive.google.com/uc?export=view&id=1LPQFUoa9HTd260w7Z23MhnFk6LtmY1qB',
   (SELECT id FROM public.categories WHERE slug = 'sopas-e-caldos'),
   'avulso', 50, true, 19),
  ('MARM 20', 'Sopa De Aipim (400G)', 'Uma opção deliciosa e reconfortante para qualquer hora do dia! Nossa sopa de aipim é cremosa, saborosa e perfeita para quem busca praticidade sem abrir mão do sabor caseiro.  ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  SOPA: 385G QUEIJO: 15G', 14.00, 'https://drive.google.com/uc?export=view&id=1-4XUbJGIlK0p_FkH5lYq9RCRCeNWxFzw',
   (SELECT id FROM public.categories WHERE slug = 'sopas-e-caldos'),
   'avulso', 50, true, 20),
  ('MARM 21', 'Fricassê De Frango Com Arroz e Batata Palha (350G)', 'Uma refeição completa, prática e cheia de sabor! Perfeita para o dia a dia, combina cremosidade, leveza e uma textura irresistível, proporcionando uma experiência deliciosa em cada garfada.  ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  ARROZ: 140G FRICASSÊ DE FRANGO: 175G QUEIJO: 15G BATATA PALHA: 20G', 15.50, 'https://drive.google.com/uc?export=view&id=1OBQWwpEoRg3MXxbj56ixY0UYn-BbcKzt',
   (SELECT id FROM public.categories WHERE slug = 'frango'),
   'avulso', 50, true, 21),
  ('MARM 22', 'Espaguete Ao Molho De Posta Desfiada e Queijo. (350G)', 'Uma refeição prática e cheia de sabor! Nosso espaguete é acompanhado por um delicioso molho de posta e finalizado com queijo, proporcionando uma combinação irresistível para o seu dia a dia.  ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  MASSA: 190G MOLHO: 145G QUIJO: 15G', 14.00, 'https://drive.google.com/uc?export=view&id=1-HqlFIb-KbvQDEY0V34yR8SuK08F5mhX',
   (SELECT id FROM public.categories WHERE slug = 'massas'),
   'avulso', 50, true, 22),
  ('MARM 23', 'Estrogonofe De Frango Com Arroz e Batata Palha (350G)', 'Uma refeição clássica, cremosa e cheia de sabor! Nosso estrogonofe de frango é perfeito para quem busca praticidade sem abrir mão de uma refeição deliciosa. Acompanha arroz, formando uma combinação irresistível para o dia a dia.  ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  ARROZ: 140G ESTROGONOFE FRANGO: 190G BATATA PALHA: 20G', 15.00, 'https://drive.google.com/uc?export=view&id=1N0zvQ8vpGIh3OMlhWHUapveCoS0JBFXo',
   (SELECT id FROM public.categories WHERE slug = 'frango'),
   'avulso', 50, true, 23),
  ('MARM 24', 'Estrogonofe De Carne Com Arroz e Batata Palha (350G)', 'Uma refeição clássica, cremosa e muito saborosa! Nosso estrogonofe de carne é preparado com molho especial e textura cremosa, perfeito para uma refeição prática e deliciosa no dia a dia. Acompanha arroz soltinho.  ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  ARROZ: 140G ESTROGONOFE: 190G BATATA PALHA: 20G', 18.50, 'https://drive.google.com/uc?export=view&id=1RSyhulqiBgIVCdf4AyEbbZcy_eoI6rvY',
   (SELECT id FROM public.categories WHERE slug = 'carne-vermelha'),
   'avulso', 50, true, 24),
  ('MARM 25', 'Bobó De Frango Com Arroz (350g)', 'Uma refeição cremosa, saborosa e cheia de tradição! Nosso bobó de frango é preparado com textura suave e sabor marcante, acompanhado de arroz soltinho, formando uma combinação perfeita para o seu dia a dia.  ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  ARROZ: 140G BOBÓ DE FRANGO: 210G', 16.00, 'https://drive.google.com/uc?export=view&id=1IjFAUWAUGTICL0jz_BriT0HRukGZEECT',
   (SELECT id FROM public.categories WHERE slug = 'frango'),
   'avulso', 50, true, 25),
  ('MARM 26', 'Carne De Panela Com Legumes,Arroz e Feijão Preto (350g)', 'Uma refeição completa, saborosa e cheia de tradição! Nossa carne de panela é macia e bem suculenta, acompanhada de legumes, arroz soltinho e feijão preto, formando um prato equilibrado e perfeito para o dia a dia.  ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  CARNE DE PANELA: 120G ARROZ: 120G FEIJÃO: 110G', 15.00, 'https://drive.google.com/uc?export=view&id=1q-VnsEcP0x1AGYrf44X9ZM9fzwYiYNnW',
   (SELECT id FROM public.categories WHERE slug = 'carne-vermelha'),
   'avulso', 50, true, 26),
  ('MARM 27', 'PICADINHO LOW CARB DE FRANGO (250G)', 'Uma refeição leve, saudável e cheia de sabor! Nosso picadinho de frango low carb é preparado com frango em pedaços e legumes selecionados, perfeito para quem busca uma alimentação equilibrada sem abrir mão da praticidade.  ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  PICADINHO DE FRANGO: 125G LEGUMES:125G', 16.00, 'https://drive.google.com/uc?export=view&id=1xg6hF3MhqvBEVjLeb3M7ibgmtDZCwbms',
   (SELECT id FROM public.categories WHERE slug = 'low-carb'),
   'avulso', 50, true, 27),
  ('MARM 28', 'PICADINHO LOW CARB DE CARNE (250G)', 'Uma refeição leve, prática e cheia de sabor! Nosso picadinho de carne low carb é preparado com carne em pedaços e legumes selecionados, ideal para quem busca uma alimentação equilibrada sem abrir mão da praticidade.  ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  PICADINHO CARNE: 125G LEGUMES: 125G', 17.00, 'https://drive.google.com/uc?export=view&id=1v6ntbJbTCGoQmFMM00qd-CcOgyD_yqSA',
   (SELECT id FROM public.categories WHERE slug = 'low-carb'),
   'avulso', 50, true, 28),
  ('MARM 29', 'Frango Xadrez (350g)', 'Uma refeição prática, saborosa e equilibrada! Combinação perfeita para o dia a dia, trazendo um prato completo, colorido e cheio de sabor.   ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  ARROZ: 140G FRANGO: 195G  AMENDOIM: 15G', 15.00, 'https://drive.google.com/uc?export=view&id=15YoeCL6SMKm3zKubM8-W7GMqNa-NVO0f',
   (SELECT id FROM public.categories WHERE slug = 'frango'),
   'avulso', 50, true, 29),
  ('MARM 30', 'Nhoque Ao Molho Branco (350G)', 'Uma refeição cremosa, saborosa e muito prática! Nosso nhoque ao molho branco é perfeito para quem busca uma opção rápida e deliciosa para o dia a dia, com textura macia e sabor irresistível.  ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  MASSA: 180G MOLHO: 155G QUEIJO: 15G', 17.00, 'https://drive.google.com/uc?export=view&id=1dQv4w4-_wK89uFZLDJsB1o_CJFOGSgHG',
   (SELECT id FROM public.categories WHERE slug = 'massas'),
   'avulso', 50, true, 30),
  ('MARM 31', 'Estrogonofe de Frango com Purê de Mandioquinha (350G)', 'Uma refeição cremosa, saborosa e muito prática! Nosso estrogonofe de frango é acompanhado de um delicioso purê de mandioquinha, formando uma combinação perfeita de sabor e textura para o seu dia a dia.  ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  ARROZ: 100G ESTROGONOFE DE FRANGO: 150G PURE DE MANDIOQUINHA: 100G', 16.00, 'https://drive.google.com/uc?export=view&id=1MNDG7KI8styZVUUS_RI6yTYqo1ymjyok',
   (SELECT id FROM public.categories WHERE slug = 'frango'),
   'avulso', 50, true, 31),
  ('MARM 32', 'Macarrão Integral Ao Molho Bolonhesa', 'Uma refeição equilibrada, saborosa e prática! Nosso macarrão integral ao molho bolonhesa é perfeito para quem busca uma opção nutritiva sem abrir mão do sabor, ideal para o dia a dia.  ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  MASSA: 165G MOLHO: 185G', 16.00, 'https://drive.google.com/uc?export=view&id=1XA5mTQNic2i0AduhndA1H2Zm-EbWEevx',
   (SELECT id FROM public.categories WHERE slug = 'massas'),
   'avulso', 50, true, 32),
  ('MARM 33', 'Escondidinho De Aipim Com Recheio de Carne Moida e Queijo (350g)', 'Uma refeição cremosa, saborosa e muito prática! Nosso escondidinho de aipim é perfeito para quem busca uma comida caseira, com textura suave e muito sabor, ideal para o dia a dia.   ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  PURÊ DE AIPIM: 215G  CARNE MOIDA: 120G QUEIJO: 15G', 16.50, 'https://drive.google.com/uc?export=view&id=1Kl72v5t2z2_Ao4QjTQo7cdJjQltfXoQl',
   (SELECT id FROM public.categories WHERE slug = 'carne-vermelha'),
   'avulso', 50, true, 33),
  ('MARM 34', 'Frango Ao Molho Com Polenta e Arroz (350g)', 'Uma refeição caseira, saborosa e muito prática! Nosso frango ao molho com polenta é uma combinação clássica, com textura cremosa e sabor marcante, perfeita para o seu dia a dia.  ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  FRANGO: 120G POLENTA: 130G ARROZ: 100G', 15.00, 'https://drive.google.com/uc?export=view&id=1pMGXwGWpcrlG9RBwkP8MWDkx4CgpCHeC',
   (SELECT id FROM public.categories WHERE slug = 'frango'),
   'avulso', 50, true, 34),
  ('MARM 35', 'Brasileirinho (350g)', 'Uma refeição simples, completa e cheia de sabor! Nosso prato brasileiro combina arroz soltinho, feijão preto e carne moída, trazendo aquele gostinho caseiro perfeito para o dia a dia.  ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  ARROZ: 130G FEIJÃO PRETO: 110G CARNE MOÍDA: 110G', 15.00, 'https://drive.google.com/uc?export=view&id=1K9Yue4UgeoRBv2TYkSEM8G2jpOUDca32',
   (SELECT id FROM public.categories WHERE slug = 'carne-vermelha'),
   'avulso', 50, true, 35),
  ('MARM 36', 'Creme De Abóbora Cabotiá (400g)', 'Um creme leve e saboroso, preparado com abóbora cabotiá e temperos frescos. Ideal para dietas equilibradas ou para aquecer nos dias frios, trazendo conforto e praticidade  ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  SOPA: 385G QUEIJO: 15G', 14.00, 'https://drive.google.com/uc?export=view&id=1doMsBmLFMYAcqZZu4zvNy3Wmu041AHDI',
   (SELECT id FROM public.categories WHERE slug = 'sopas-e-caldos'),
   'avulso', 50, true, 36),
  ('MARM 37', 'Nhoque Ao Molho Bolonhesa (350G)', 'Uma refeição clássica, saborosa e muito prática! Nosso nhoque à bolonhesa combina massa macia com um molho encorpado e delicioso, perfeito para o dia a dia.  ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  MASSA: 180G MOLHO: 155G QUEIJO. 15G', 17.00, 'https://drive.google.com/uc?export=view&id=12SqKDIFnAIj74y7pPGsc6oJI0U7yHwf5',
   (SELECT id FROM public.categories WHERE slug = 'massas'),
   'avulso', 50, true, 37),
  ('MARM 38', 'Escondidinho De Abóbora Com Frango e queijo (300g)', 'Uma refeição leve, saborosa e muito prática! Nosso escondidinho de abóbora com frango combina cremosidade e sabor caseiro, perfeito para o dia a dia ou para uma refeição mais equilibrada.  ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  FRANGO: 110G PURÊ DE ABÓBORA: 175G QUEIJO: 15G', 14.00, 'https://drive.google.com/uc?export=view&id=1fZ9ln8ZKXL3l_g2ce6cX1ICZtgyvAXm4',
   (SELECT id FROM public.categories WHERE slug = 'frango'),
   'avulso', 50, true, 38),
  ('MARM 39', 'ESCONDIDINHO DE BATATA DOCE COM FRANGO (350G)', 'Uma refeição leve, saborosa e muito prática! Nosso escondidinho de batata-doce com frango é perfeito para quem busca uma opção equilibrada, com textura cremosa e sabor caseiro.  ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  FRANGO: 110G PURE DE BATATA DOCE: 220G QUEIJO: 20G', 15.00, 'https://drive.google.com/uc?export=view&id=1lTjz9xlSzZRYohhbcsq4xJk5tKUabyip',
   (SELECT id FROM public.categories WHERE slug = 'frango'),
   'avulso', 50, true, 39),
  ('MARM 40', 'Estrogonofe De Salmão (350G)', 'Uma opção sofisticada, leve e muito saborosa! Nosso estrogonofe de salmão é cremoso, delicado e perfeito para quem busca uma refeição prática sem abrir mão do sabor.  ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  ARROZ: 140G ESTROGONOFE SALMÃO 190G BATATA PALHA: 20G', 16.00, 'https://drive.google.com/uc?export=view&id=1Y83H7fZnOHvsFNEI2Xq4y1pmMxUhgUcf',
   (SELECT id FROM public.categories WHERE slug = 'peixe'),
   'avulso', 50, true, 40),
  ('MARM 41', 'GALINHADA (300G)', 'Uma refeição tradicional, prática e cheia de sabor! Perfeita para o dia a dia, com aquele gostinho caseiro que traz conforto e satisfação em cada porção.  ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  GALINHADA: 300G', 14.00, 'https://drive.google.com/uc?export=view&id=1-mWblAwvctRtPyHacaQEBZ5WpA_9W9uY',
   (SELECT id FROM public.categories WHERE slug = 'frango'),
   'avulso', 50, true, 41),
  ('MARM 42', 'Sobrecoxa Com Creme De Milho (350G)', 'Uma refeição deliciosa, cremosa e muito prática! Combinação perfeita para o dia a dia, trazendo sabor caseiro e conforto em cada porção  ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  ARROZ: 120G SOBRECOXA: 120G CREME DE MILHO: 110G', 15.00, 'https://drive.google.com/uc?export=view&id=1zEq5NpVYHPX-IGq5rXwwgoO5Uyr8Udgd',
   (SELECT id FROM public.categories WHERE slug = 'frango'),
   'avulso', 50, true, 42),
  ('MARM 43', 'CALDO VERDE (400G)', 'Uma opção tradicional, saborosa e muito reconfortante! Nosso caldo verde é cremoso e perfeito para aquecer seus dias com praticidade e aquele gostinho caseiro que todo mundo ama.  ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  SOPA:400G', 14.00, 'https://drive.google.com/uc?export=view&id=1764TwIKk_hMyOcHowt0j_ypia5N8aodu',
   (SELECT id FROM public.categories WHERE slug = 'sopas-e-caldos'),
   'avulso', 50, true, 43),
  ('MARM 44', 'FEIJOADA', 'Uma refeição tradicional brasileira, rica em sabor e muito prática! Nossa feijoada é encorpada, bem temperada e perfeita para momentos especiais ou para o dia a dia.  ALÉRGICOS: Pode conter leite, ovos, derivados de trigo, soja, amendoim e peixe. PODE CONTER LACTOSE. PODE CONTER GLÚTEN.  ARROZ: 140G FEIJOADA: 190G COUVE: 20G', 15.50, 'https://drive.google.com/uc?export=view&id=1sCUh8Z4U1AaelXwskpG4T1q_mMyp5OJ1',
   (SELECT id FROM public.categories WHERE slug = 'carne-vermelha'),
   'avulso', 50, true, 44),
  ('MARM 45', 'COMBO DE 10 MARMITAS', 'INFORMAÇÕES IMPORTANTES SOBRE OS COMBOS  • Os combos são pacotes fechados, portanto não realizamos trocas de itens.  • Os combos são montados conforme a disponibilidade do estoque do dia, podendo ocorrer alterações nos itens diariamente. O cliente receberá os produtos disponíveis no cardápio do dia. • Consulte o valor do frete para o seu endereço. 1 Moída com Legumes e arroz. (350g)  1 Escondidinho de batata doce com carne moída e queijo.(350g)  1 Sobrecoxa com creme de milho e arroz (350g)  1 Frango xadrez  com arroz  (350g)  1  Estrogonofe de frango com arroz e batata palha (350g)  1 carne de panela com legumes,arroz  e feijão preto (350g)  1 Fricassê de frango com arroz e batata palha(350g)  1 Brasileirinho Fit Frango isca com cenoura,arroz e feijão carioca (300g) 1 Arroz Carreteiro(350g) 1 espaguete com carne bovina desfiada molho de tomate artesanal e queijo  (350g)', 141.90, 'https://drive.google.com/uc?export=view&id=1Yk05ikRuU1QQpXY57FF5GznMtGzvEezh',
   (SELECT id FROM public.categories WHERE slug = 'combos'),
   'combo', 50, true, 45),
  ('MARM 46', 'COMBO DE 10 SOPAS', '2 sopa de Aipim (creme de aipim, carne bovina desfiada, bacon e queijo) (400g) 2 caldo verde (creme de batata inglesa, bacon, calabresa e couve)  (400g)  2 Creme de milho com queijo (400g) 2 sopa eslava (creme de batata inglesa com iscas de carne bovina e queijo) (400g) 2 sopa de abóbora (creme de abóbora com frango desfiado e queijo) (400g)', 129.90, 'https://drive.google.com/uc?export=view&id=1V1K7JHilxvHYmqKlEShac486VlEQU_Nc',
   (SELECT id FROM public.categories WHERE slug = 'combos'),
   'combo', 50, true, 46),
  ('MARM 47', 'COMBO 5 DIAS NO FOCO', 'INFORMAÇÕES IMPORTANTES SOBRE OS COMBOS  * Os combos são pacotes fechados, portanto não realizamos trocas de itens.  * Os combos são montados conforme a disponibilidade do estoque do dia, podendo ocorrer alterações nos itens diariamente. O cliente receberá os produtos disponíveis no cardápio do dia. * Consulte o valor do frete para o seu endereço.   1 Galinhada(300g)  1 estrogonofe de frango com arroz e batata palha (350g) 1 frango xadrez com arroz (350g)  1 Espaguete integral com molho bolonhesa (350g) 1 Brasileirinho Fit frango isca,com arroz e feijão carioca (300g) 1 brasileirinho (carne moída com arroz e feijão)  (350g) 1 moída com legumes e purê de abóbora(350g)  1 Moída com legumes e arroz (350g)  1 Carne de panela com legumes e arroz (350g)  1 panqueca de frango, molho de tomate e queijo (300g)', 143.90, 'https://drive.google.com/uc?export=view&id=1auxHkhvcBDrO9CsdL80hnabe2oke40cR',
   (SELECT id FROM public.categories WHERE slug = 'combos'),
   'combo', 50, true, 47),
  ('MARM 48', 'COMBO PREMIUM', 'INFORMAÇÕES IMPORTANTES SOBRE OS COMBOS  * Os combos são pacotes fechados, portanto não realizamos trocas de itens.  * Os combos são montados conforme a disponibilidade do estoque do dia, podendo ocorrer alterações nos itens diariamente. O cliente receberá os produtos disponíveis no cardápio do dia. * Consulte o valor do frete para o seu endereço.  2 Estrogonofe de carne com arroz branco e batata palha (350g)  2 feijoada (350g)  1 estrogonofe de salmão com arroz branco e batata palha (350g) 1 Nhoque ao molho Branco e queijo. (350g) 1 tilápia com molho siciliano, mix de legumes e arroz (350g) 1 bife a rolê com arroz e feijão (350g) 1 Panqueca de carne e queijo (300g)  1 Panqueca de frango e queijo (300g)', 165.90, 'https://drive.google.com/uc?export=view&id=1vzNp5G-lwxCTTZDPSbWlOFRInlcY5V00',
   (SELECT id FROM public.categories WHERE slug = 'combos'),
   'combo', 50, true, 48),
  ('MARM 49', 'COMBO QUERIDINHO NUTRI', 'INFORMAÇÕES IMPORTANTES SOBRE OS COMBOS  * Os combos são pacotes fechados, portanto não realizamos trocas de itens.  * Os combos são montados conforme a disponibilidade do estoque do dia, podendo ocorrer alterações nos itens diariamente. O cliente receberá os produtos disponíveis no cardápio do dia. * Consulte o valor do frete para o seu endereço.  1 panqueca de carne, molho de tomate e queijo (300g) 1 panqueca de frango, molho de tomate e queijo (300g) 2 Moída com legumes e purê de batata doce  (350g) 2 spaghetti carne bovina desfiada molho de tomate artesanal e queijo (350g)  2 Carne de panela com legumes,arroz e feijão preto.(350g) 2 Galinhada(300g)  2 brasileirinho Fit (frango isca grelhado com arroz e feijão) (350g) 2 fricassê de frango com arroz e batata palha (350g)', 199.90, 'https://drive.google.com/uc?export=view&id=1XYeHMe0qbGsY8VntX92s31UkRBTSvotE',
   (SELECT id FROM public.categories WHERE slug = 'combos'),
   'combo', 50, true, 49),
  ('MARM 50', 'COMBO 12 REFEIÇÕES 3 SOPAS', 'INFORMAÇÕES IMPORTANTES SOBRE OS COMBOS  * Os combos são pacotes fechados, portanto não realizamos trocas de itens.  * Os combos são montados conforme a disponibilidade do estoque do dia, podendo ocorrer alterações nos itens diariamente. O cliente receberá os produtos disponíveis no cardápio do dia. * Consulte o valor do frete para o seu endereço.  2 Arroz Carreteiro(350g)  2 spaghetti com carne bovina desfiada ao molho de tomate e queijo (350g)  2 fricassê de frango com arroz e batata palha (350g) 2 Frango xadrez com arroz  (350g) 2 sobrecoxa de frango com creme de milho e arroz (350g) 2 Brasileirinho (carne moída com arroz e feijão). (350g)  SOPAS 1 sopa eslava (creme de batata inglesa com isca de carne bovina e queijo)  (400g) 1 sopa de aipim (creme de aipim com carne bovina desfiada, bacon e queijo)  (400g) 1 Sopa de abóbora (creme de abóbora com frango desfiado e queijo)', 202.90, 'https://drive.google.com/uc?export=view&id=1JaJg0qFAoGD0BgyaHlGPiJXJ6Z7-UCvz',
   (SELECT id FROM public.categories WHERE slug = 'combos'),
   'combo', 50, true, 50),
  ('MARM 51', 'COMBO 16 REFEIÇÕES E 4 SOPAS', 'INFORMAÇÕES IMPORTANTES SOBRE OS COMBOS  * Os combos são pacotes fechados, portanto não realizamos trocas de itens.  * Os combos são montados conforme a disponibilidade do estoque do dia, podendo ocorrer alterações nos itens diariamente. O cliente receberá os produtos disponíveis no cardápio do dia. * Consulte o valor do frete para o seu endereço.  2 Arroz Carreteiro(350g) 2 Frango Xadrez com arroz (350g) 2 fricassê de frango com arroz branco batata palha (350g) 2 brasileirinho (carne moída com arroz e feijão).(350g) 2 spaghetti com carne bovina desfiada molho de tomate artesanal e queijo (350g) 2 feijoada  (350) 2 Sobrecoxa com Creme de milho (350g) 2 Carne de panela com legumes,arroz e feijão preto. (350g)   Sopas  1 sopa de aipim (creme de aipim com carne bovina desfiada, bacon e queijo) (400g) 1 sopa de abóbora (creme de abóbora com frango desfiado e queijo) (400g) 1 sopa eslava (creme de batata inglesa com isca de carne bovina e queijo) (400g) 1 caldo verde (creme de batata inglesa com bacon, calabresa, couve) (400g)', 262.90, 'https://drive.google.com/uc?export=view&id=1XrI2zLrydh8J6dBGtLXEE3Lsqh4gjJKI',
   (SELECT id FROM public.categories WHERE slug = 'combos'),
   'combo', 50, true, 51),
  ('MARM 52', 'COMBO 20 REFEIÇÕES', 'INFORMAÇÕES IMPORTANTES SOBRE OS COMBOS  * Os combos são pacotes fechados, portanto não realizamos trocas de itens.  * Os combos são montados conforme a disponibilidade do estoque do dia, podendo ocorrer alterações nos itens diariamente. O cliente receberá os produtos disponíveis no cardápio do dia. * Consulte o valor do frete para o seu endereço.  2 spaghetti com carne bovina desfiada, molho de tomate artesanal e queijo. (350g) 2 Frango Xadrez com arroz (350g)  2 Arroz Carreteiro(350g)  2 feijoada(350g)  2 Escondidinho de aipim com carne moída e queijo (350g) 2 Sobrecoxa com creme de milho e arroz  (350g)  2 Fricassê de frango com arroz e batata palha (350g)  2 Brasileirinho Fit (frango isca com arroz e feijão) 300g)   2 brasileirinho (carne moída com arroz e feijão). (350g) 2 Carne de panela com legumes,arroz e feijão preto  (350g)', 289.90, 'https://drive.google.com/uc?export=view&id=1QiwjmMTE4ZYt94i8Pyy27ezh9DZlRPnm',
   (SELECT id FROM public.categories WHERE slug = 'combos'),
   'combo', 50, true, 52),
  ('MARM 53', 'FEIJÃO PRETO', 'FEIJÃO PRETO 200G', 3.50, 'https://drive.google.com/uc?export=view&id=1jW0q7tmlfYvDz6Ug29AH_fo61qZYTK2U',
   (SELECT id FROM public.categories WHERE slug = 'adicionais'),
   'avulso', 50, true, 53),
  ('MARM 54', 'MIX DE LEGUMES', 'CENOURA,VAGEM E GRÃO DE BICO (150G)', 4.50, 'https://drive.google.com/uc?export=view&id=1KhHHUkxSd5tl0ozHbWaUwcnrNn2Luvqn',
   (SELECT id FROM public.categories WHERE slug = 'adicionais'),
   'avulso', 50, true, 54),
  ('MARM 55', 'MIX DE LEGUMES NA MANTEIGA', '(150G)', 5.50, 'https://drive.google.com/uc?export=view&id=1RTlb_BUTxlvPVtgM-abOW-PEmhA01yon',
   (SELECT id FROM public.categories WHERE slug = 'adicionais'),
   'avulso', 50, true, 55),
  ('MARM 56', 'ARROZ BRANCO', 'ARROZ BRANCO. (150G)', 4.00, 'https://drive.google.com/uc?export=view&id=1VNly0Zv2Fpcs1LMslTnOXrnH1Zz3dMUZ',
   (SELECT id FROM public.categories WHERE slug = 'adicionais'),
   'avulso', 50, true, 56),
  ('MARM 57', 'FEIJÃO CARIOCA', 'FEIJÃO CARIOCA (200G)', 3.50, 'https://drive.google.com/uc?export=view&id=1RxKPidqhbKObjergBfZW4ImVfVifyZBU',
   (SELECT id FROM public.categories WHERE slug = 'adicionais'),
   'avulso', 50, true, 57)
ON CONFLICT (sku) DO UPDATE SET
  name        = EXCLUDED.name,
  description = EXCLUDED.description,
  price       = EXCLUDED.price,
  image_url   = EXCLUDED.image_url,
  category_id = EXCLUDED.category_id,
  stock_type  = EXCLUDED.stock_type,
  sort_order  = EXCLUDED.sort_order;